Added userdata in user information
profcomff/auth-lib pull request #37
Opened 2023-07-29 18:20 UTC by Temmmmmo

## Изменения
Добавлена возможность получить информацию о пользователе из [`userdata-api`](https://github.com/profcomff/userdata-api).

## Реализации
1. Реализованы синхронный и асинхронный методы получения информации о пользователе из [`userdata-api`](https://github.com/profcomff/userdata-api).
2. Добавлен параметр `enable_user_data`, позволяющий получать информацию о пользователе из [`userdata-api`](https://github.com/profcomff/userdata-api), в метод инициализации основного класса `UnionAuth` библиотеки [`auth-lib`](https://github.com/profcomff/auth-lib).
3. Добавлен новый параметр user_data_url, принимающий ссылку на [`userdata-api`](https://github.com/profcomff/userdata-api).

## Детали
1. Старый параметр `url` заменен на `auth_url`. Так как в старой версии в 'url' передавалась ссылка на  [`auth-api`](https://github.com/profcomff/auth-api).
2. В глобальные настройки также добавлены поля `USER_DATA_URL` и `ENABLE_USER_DATA`.

## Check-List
- [x] Вы проверили свой код перед отправкой запроса?
- [x] Вы написали тесты к реализованным функциям? - **не требуется**
- [x] Вы не забыли применить black и isort?

2023-07-29 18:27 UTC, grigoriev-semyon requested changes

2023-07-29 18:27 UTC, grigoriev-semyon commented on auth_lib/fastapi.py
>      async def __call__(
метод не нужен у тебя уже есть он

2023-07-29 18:27 UTC, grigoriev-semyon commented on auth_lib/aiomethods.py
> +                raise IncorrectData(response=response.json()["body"])
ошибок не надо

2023-07-29 18:30 UTC, grigoriev-semyon commented on auth_lib/fastapi.py
> +        user_data_url=None,
userdata_url

2023-07-29 18:30 UTC, Temmmmmo commented on auth_lib/fastapi.py
>      async def __call__(
я не буду срать в код

2023-07-29 18:32 UTC, grigoriev-semyon commented on auth_lib/fastapi.py
> +        return None
убери в метод который вызываешь

2023-07-29 18:36 UTC, grigoriev-semyon commented on auth_lib/aiomethods.py
> +        user_get = await self.check_token(token)
лишнее

2023-07-29 18:42 UTC, Temmmmmo commented on auth_lib/aiomethods.py
> +                raise IncorrectData(response=response.json()["body"])
исправил

2023-07-29 18:42 UTC, Temmmmmo commented on auth_lib/fastapi.py
> +        user_data_url=None,
исправил

2023-07-29 18:43 UTC, Temmmmmo commented on auth_lib/aiomethods.py
> +        user_get = await self.check_token(token)
исправил

2023-07-29 18:43 UTC, Temmmmmo commented on auth_lib/fastapi.py
> +        return None
кого убрать? проверку на enable?

2023-07-31 12:54 UTC, grigoriev-semyon requested changes

2023-07-31 12:54 UTC, grigoriev-semyon commented on auth_lib/aiomethods.py
> +                url=f"{self.userdata_url}/user/{user_id}", headers=headers
давай тут urljoin

2023-07-31 12:54 UTC, grigoriev-semyon commented on auth_lib/fastapi.py
> +        result["userdata"] = user_data_info
а может сразу по ключу положить ``items``?

2023-07-31 13:56 UTC, Temmmmmo commented on auth_lib/aiomethods.py
> +                url=f"{self.userdata_url}/user/{user_id}", headers=headers
исправил

2023-07-31 13:57 UTC, Temmmmmo commented on auth_lib/fastapi.py
> +        result["userdata"] = user_data_info
можно и их
исправил

2023-07-31 13:58 UTC, Temmmmmo commented on auth_lib/methods.py
> +            url=f"{self.userdata_url}/user/{user_id}", headers=headers
исправил

2023-07-31 14:13 UTC, grigoriev-semyon requested changes

2023-07-31 14:13 UTC, grigoriev-semyon commented on auth_lib/fastapi.py
> +        if user_data_info is None and self.enable_userdata:
ты написал патч который  юзердате кинет 404 если инфы нет
но тут если инфы нет оно упадет
это норм поведение?

2023-07-31 14:14 UTC, grigoriev-semyon commented on auth_lib/fastapi.py
> +        if user_data_info is None and self.enable_userdata:
это все таки не токен которого если нет то должно падать
это именно данные которых может не быть и это норма

2023-07-31 15:53 UTC, Temmmmmo commented on auth_lib/fastapi.py
> +        if user_data_info is None and self.enable_userdata:
исправил

2023-08-04 14:08 UTC, grigoriev-semyon approved these changes

2023-08-04 14:08 UTC, merged